maps:
  indoor:
    map_yaml: "indoor_map_final.yaml"

    start:
      x: 0.156
      y: -0.2154
      yaw: -0.0761


    elevator_btn_front:
      x: 5.60
      y: -1.20
      yaw: 0.0082


    unload_spot:
      x: 4.71
      y: -0.104
      yaw: -3.1000